# print('Вывод', 'данных', 'через', 'запятую')
# print()  - добавляет пустую строку
# print('1', '2', '3', '4')
# print("Здравствуй, мир!")
# print('4', '8', '15', '16', '23', '42')
# print('4')
# print('8')
# print('15')
# print('16')
# print('23')
# print('42')
# print('*')
# print('**')
# print('***')
# print('****')
# print('*****')
# print('******')
# print('*******')
# print('Как тебя зовут?')
# name = input()
# print('Привет,', name)
# name = input('Как тебя зовут??? ')
# print('Привет,', name)
name = input('Введите имя')
print(name, '- Привет')